sudo: false

branches:
  only:
  - master
  - /^greenkeeper/.*$/

language: node_js

matrix:
  include:
    - node_js: "4"
    - node_js: "6"
      env: COVERALLS=1
    - node_js: "8"

install:
  - npm install
  - lerna bootstrap

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then
      npm i coveralls;
      npm run cover && nyc report --reporter=text-lcov | coveralls;
    fi
